#!/usr/bin/env php

<?php

require 'vendor/autoload.php';

if (empty($data = getDataFromOpCli())) {
    writeln("No items found.");
    exit(1);
}

$urls = extractWebsiteEntries($data);
$failed = filterFailingUrls($urls);

echo "\n\n-- The following URLs seem inexistent. --\n\n";

array_walk($failed, 'writeln');
